### ISSUE TITLE
Unable to start docker

### ISSUE THREAD

**Issue by ramyaamar** [JBEI/edd#1]
Hi,

I wanted to install EDD, after installing Docker i tried following command
. init-config

It throws 

root@:~/edd-master/docker_services# . init-config
-su: [: -eq: unary operator expected
TODO: interactive prompt for user name and email

Kindly let me know why this error is coming.
Thanks in advance.

**Comment by wmorrell** [comment]
That should only come up if there is no `git` on your `$PATH`, or `git` is not properly configured with your name and email. What shell are you running?

Try running `. init-config --user "YOUR NAME" --email "YOU@DOMAIN.TLD"`

**Comment by ramyaamar** [comment]
Hi, thanks for your reply.

I managed to get it installed and the docker is up and running.

I am not able to view the website from browser

not able to telnet to my server ip address on port 80 and 443

when I did curl on the server itself I am seeing bad gateway error

curl -I http://localhost
HTTP/1.1 503 Service Temporarily Unavailable
Server: nginx/1.11.12
Date: Wed, 05 Apr 2017 15:01:23 GMT
Content-Type: text/html
Content-Length: 214
Connection: keep-alive

May I know how to debug the log of the backend server running.

**Comment by wmorrell** [comment]
Please see the documentation under the `docs` folder. The instructions there describe how to use the `docker` and `docker-compose` commands to interact with the containers, and extra configurations needed. I cannot tell without seeing your `docker-compose.override.yml` but I suspect the default config of only exposing HTTP ports on loopback is why you cannot connect. The problem connecting locally is likely from the `VIRTUAL_HOST` environment, we recently changed how the nginx config files are built to use [jwilder/nginx-proxy][1] and the generated file uses that environment to build the `server` blocks. 

[1]:  https://github.com/jwilder/nginx-proxy
