### ISSUE TITLE
Email Verification Issue

### ISSUE THREAD

**Issue by TylerReaganUCSD** [JBEI/edd#6]
Hello again. I have been taking more time to familiarize myself with the system so hopefully things are easier for you to explain this time. I am currently facing issues with the email verification process. There are a few things to note:

1. No email for verification is ever sent from my standalone instance
2. Accounts created on the public EDD instance are recognized as existing but not verified on my standalone instance
3. Creating a superuser with an email matching that of an account I have made on the public site seems to cause a duplicate key error (checked this by looking at the postgresql docker logs)

It seems I am stuck between a rock and a hard place where it recognizes I have existing accounts but that they are not verified. This initial recognition leads to postgresql errors so I am looking for perhaps some guidance on how best to resolve this issue. Thank you again for your time and consideration.

**Comment by wmorrell** [comment]
There is a simple SMTP server included in the EDD stack. Check the logs on the `smtp` service to see if any errors occur in sending the emails out. I would guess that AWS locks down traffic from EC2 instances on ports 22 and 587, in favor of their own metered mailing services. If so, you will need to override settings in the `local.py` file relating to Django email: https://docs.djangoproject.com/en/2.2/topics/email/

**Comment by TylerReaganUCSD** [comment]
Ah yes! It looks like you were right about the SMTP being the failing point. Here is the log output pertaining to the error:

```
290 delivering 1hlbFL-00004f-DO
  290 R: dnslookup for tylerreagan98@gmail.com
  291 T: remote_smtp for tylerreagan98@gmail.com
  291 Connecting to gmail-smtp-in.l.google.com [2607:f8b0:4001:c12::1a]:25 ... failed: Cannot assign requested address
  291 LOG: MAIN
  291   H=gmail-smtp-in.l.google.com [2607:f8b0:4001:c12::1a] Cannot assign requested address
  291 Connecting to gmail-smtp-in.l.google.com [108.177.112.27]:25 ... failed: Connection timed out (timeout=5m)
  291 LOG: MAIN
  291   H=gmail-smtp-in.l.google.com [108.177.112.27] Connection timed out
  291 Connecting to alt1.gmail-smtp-in.l.google.com [2607:f8b0:400c:c11::1a]:25 ... failed: Cannot assign requested address
  291 LOG: MAIN
  291   H=alt1.gmail-smtp-in.l.google.com [2607:f8b0:400c:c11::1a] Cannot assign requested address
  291 Connecting to alt1.gmail-smtp-in.l.google.com [173.194.212.27]:25 ... failed: Connection timed out (timeout=5m)
  291 LOG: MAIN
  291   H=alt1.gmail-smtp-in.l.google.com [173.194.212.27] Connection timed out
  291 Connecting to alt2.gmail-smtp-in.l.google.com [2800:3f0:4003:c00::1a]:25 ... failed: Cannot assign requested address
  291 LOG: MAIN
  291   H=alt2.gmail-smtp-in.l.google.com [2800:3f0:4003:c00::1a] Cannot assign requested address
  291 Connecting to alt3.gmail-smtp-in.l.google.com [2a00:1450:400b:c00::1b]:25 ... failed: Cannot assign requested address
  291 LOG: MAIN
  291   H=alt3.gmail-smtp-in.l.google.com [2a00:1450:400b:c00::1b] Cannot assign requested address
  291 Connecting to alt4.gmail-smtp-in.l.google.com [2a00:1450:400c:c08::1b]:25 ... failed: Cannot assign requested address
  291 LOG: MAIN
  291   H=alt4.gmail-smtp-in.l.google.com [2a00:1450:400c:c08::1b] Cannot assign requested address
  290 LOG: MAIN
  290   == tylerreagan98@gmail.com R=dnslookup T=remote_smtp defer (99): Cannot assign requested address
```

The Django docs seem very thorough so thank you for that link! I am sorry that I have to ask another stupid question... but where would the `local.py` file you are referring to be contained? There is not one in any of the containers even when accessing them through `docker-compose exec <container>`. I know your docs are not aimed at beginners like myself, but combing through them, I was unable to find any direction as to where `local.py` might be. Thank you again for all of your help and patience. It is greatly appreciated!!

**Comment by wmorrell** [comment]
This AWS forum post implies that there is some setup needed to allow SMTP servers to operate on EC2:
https://forums.aws.amazon.com/message.jspa?messageID=317525

In the cloned repo, the path is `server/edd/settings/local.py`; by default it is not tracked by `git` and gets generated from `server/edd/settings/local.py-example` at startup if one does not already exist.

Inside the containers, the path is `/code/edd/settings/local.py`. Note any changes here will not persist, unless you are volume mounting the `server` directory as `/code` when the container launches.
