### ISSUE TITLE
Possible to Remove Email Verification?

### ISSUE THREAD

**Issue by TylerReaganUCSD** [JBEI/edd#8]
Hi there. I have spent a lot of time going through all of your code and appreciate all the patience you have had in assisting me so far. I feel much better equipped to tackle problems now. A question I have been trying to answer is whether it would be possible to remove the email verification step required for first logins. AWS naturally throttles all traffic along port 25 so I attempted to use my company's internal smarthost as a relay using a different docker image than the tianon one you used (I used https://github.com/namshi/docker-smtp). The only issue is that now instead of redirecting me to the email verification page and sending out a verification email that gets blocked, the site encounters a 500 error and takes me to the error page. At this point, I am just wondering if it would be possible to remove the need for email verification altogether since this is only for internal local use and I would really like to be able to login as an admin user and start testing at this point. Thanks for your help, and let me know if you need any clarification!

**Comment by wmorrell** [comment]
Add a local override to setting `ACCOUNT_EMAIL_VERIFICATION` to `"optional"` or `"none"`. 

[https://django-allauth.readthedocs.io/en/latest/configuration.html]

**Comment by TylerReaganUCSD** [comment]
I tried this actually by setting `ACCOUNT_EMAIL_VERIFICATION` to `"none"` within `/server/edd/settings/auth.py` and yet there was no effect. Perhaps I am not changing the setting in the correct file or missing an override, but I have been searching and can find no other mention of this setting in the code. According to the comments in the mentioned file, I am in the correct section for Django Allauth Settings. There is mention of these settings applying IFF base.py has allauth under its installed apps but it seems it is already there by default.

**Comment by wmorrell** [comment]
Override settings should go in `local.py`, so they do not get squashed or require manual merging when the code updates. See the code in `edd/settings/__init__.py`, it loads everything from the checked-in settings files, then attempts to load `local.py` last; the values in that file take precedence.

Settings are loaded by Django during server startup. Changing a settings code file with the server still running will have no effect. Changing *any* code with the server still running will have no effect. Code is loaded at startup, so any changes requires restarting the Django process.

**Comment by TylerReaganUCSD** [comment]
I am really sorry if this is just due to me lacking basic experience, but I have been continuing to try and get the setting to read and have had no luck. Here is the code I put at the top of `local.py`:

```
import environ
import errno
import os

# Use everything in the common settings file
from .base import *  # noqa: F403

root = environ.Path(__file__) - 3  # we get this out of `from .base import *` too

# override the default Django Allauth Settings
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
ACCOUNT_EMAIL_VERIFICATION = "none"
```

To preface, I am making sure to `docker-compose down` and then `docker-compose up -d` for all of my changes so that they are registered. Just to cover all my bases, I run `docker restart container [container]` as well. Adding these lines to `local.py` still did not change the applications behavior of redirecting me to the "Verify Your E-mail Address" page every time I log in. Just to try and cover my bases even more, I also tried just removing the overrode settings from `auth.py` altogether and just having them be present in `local.py` as you see above. This too did not change the application's behavior. I am sure I am just missing some critical and obvious step to getting these settings to take effect, but I have not been able to find any resources that would suggest what I am doing is incorrect. Thank you again for your patience with me.

**Comment by wmorrell** [comment]
Are you sure the modified code is actually running? By default the container runs with the release version of code contained in the image. If you are modifying the code to run, it has to be loaded in a volume mounted to `/code` inside the container. Modifying code inside the container and then restarting will have no effect; Docker will just discard the changes from the old container and launch again from a fresh copy of the image.

**Comment by TylerReaganUCSD** [comment]
I have been spending my time better familiarizing myself with all the moving parts to hopefully make your job easier. I just have a clarifying question. To me, it seems that two major methods have been mentioned:

1. creating a local copy of the `server` directory, modifying the settings within this directory (by changing its `local.py`, and then mounting this directory to `/code` by having the following code present within the `edd`, `websocket`, and `worker` containers of `docker-compose.override.yml` like so:

```
volumes:
       /path/to/modified/local/server/dir:/code
```
Then I would simply run `docker-compose up -d` as normal and the override file would then make sure that my modified code is mounted and used. I have tried this and my containers do not run properly. Commenting out the edited lines in my override file and trying to run things normally again also seems to leave my nginx container in a restart loop so I am forced to wipe and pull the code from GitHub again.

2. create a local copy of `local.py` and modify this file with the desired settings changes, mount this file to the `edd` (possibly `websocket` and `worker` containers too?) in `docker-compose.override.yml` like so:

```
volumes:
       /full/path/to/my/modified/local/local.py:/etc/myorg/edd/local.py
```
I assume the mount path `/etc/myorg/edd/local.py` is exactly the mount path I should use but with `myorg` changed to my actual org. It seems that this method also requires running the command `run docker --local /etc/myorg/edd/local.py -w edd application`. Will this command replace the functionality of `docker-compose up -d`? It seems to me that I now must run a `docker run` command for every container. Or is there some other sequence of docker run/compose commands that I should be using alongside the given command for this solution? 

I imagine that the first option should be used when looking to replace the actual code of the container (say to customize the front-end or perhaps alter the way that the pipelines work?) and that the second option is what should be used for altering just the settings of the application. I am aware that the bulk of my questions should probably be common sense for anyone more familiar with Docker so I apologize for taking up so much time and thank you again for your patience. Hopefully my issues will make things easier for those trying to run EDD in the cloud in the future.
