### ISSUE TITLE
Unable to bring up edd container

### ISSUE THREAD

**Issue by blenglee** [JBEI/edd#80]
Hi,

Starting fresh from a new environment, I followed the steps that you have suggested in the previously closed issue. My objective is simple, to set up a local EDD instance.

When I run docker compose up -d, the container exited immediately as shown below. 
As the log output does not shed much information, will like to know where I am missing in the setup.
I will appreciate if there is a getting started doc that you can point me to for step by step on how to set up EDD. The current README.md is very high level. 

Thank you for your help.

Here are the steps:
Step 1: Clone the edd source
git clone https://github.com/JBEI/edd.git

Step 2: Build local image
DOCKER_BUILDKIT=1 docker build -t jbei/edd-core -f docker/edd/core/Dockerfile .

Step 3: Launch EDD
docker compose up -d

## OUTPUT ##
%docker compose up -d
[+] Running 6/6
 ⠿ Network edd_backnet           Created                                                     0.1s
 ⠿ Volume "edd_edd_attachments"  Created                                                     0.0s
 ⠿ Volume "edd_edd_staticfiles"  Created                                                     0.0s
 ⠿ Container edd-http-1          Started                                                     1.9s
 ⠿ Container edd-websocket-1     Started                                                     2.0s
 ⠿ Container edd-worker-1        Started                                                     1.8s

>>> Here the docker compose logs -f showed the containers exited right away

% docker container ls -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS                     PORTS     NAMES
e78c5bfb9057   jbei/edd-core:latest   "/usr/bin/tini -- /u…"   4 minutes ago   Exited (1) 4 minutes ago             edd-worker-1
c21068a2b43f   jbei/edd-core:latest   "/usr/bin/tini -- /u…"   4 minutes ago   Exited (1) 4 minutes ago             edd-http-1
b5fce90cfa03   jbei/edd-core:latest   "/usr/bin/tini -- /u…"   4 minutes ago   Exited (1) 4 minutes ago             edd-websocket-1

% docker image ls
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
jbei/edd-core   latest    8281568befa3   10 minutes ago   711MB

# To check the logs
docker compose logs -f  

edd-worker-1  | + invoke celery
edd-worker-1  | Running with container copy of code …
edd-http-1    | + invoke gunicorn
edd-http-1    | Running with container copy of code …
edd-websocket-1  | + invoke daphne
edd-websocket-1  | Running with container copy of code …
edd-worker-1 exited with code 1
edd-http-1 exited with code 1
edd-websocket-1 exited with code 1

This is all I have from the compose logs. There is not much details.

**Comment by wmorrell** [comment]
Did you run the quickstart script to generate the `docker-compose.override.yml` file and generate secrets for local development? EDD must run with a database, cache, and message queue. The base `docker-compose.yml` file only launches the core EDD code, to allow for those services to be provided elsewhere. But they need to be present for EDD to function.

**Comment by blenglee** [comment]
Happy to report here that I made much more progress with your help.
Here is what I did:

Step 1: Clone the edd source
git clone https://github.com/JBEI/edd.git

Step 2: ./bin/dev_quickstart.sh 

Step 3: ./bin/dev_build.sh (same as building the docker image)

Step 4: docker compose up -d

I am seeing 2 containers exited and will like to get your advice to fix them.


CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS                      PORTS                                                 NAMES
4e61e9d47c8d   jbei/nginx-gen:latest                 "/usr/local/bin/entr…"   31 minutes ago   Up 31 minutes                                                                     edd-nginx-gen-1
bbdcec022a65   jbei/edd-core:latest                  "/usr/bin/tini -- /u…"   31 minutes ago   Exited (1) 31 minutes ago                                                         edd-worker-1
5a4cdf66428a   jbei/edd-core:latest                  "/usr/bin/tini -- /u…"   31 minutes ago   Exited (1) 31 minutes ago                                                         edd-websocket-1
a6350bd6f21b   jbei/edd-core:latest                  "/usr/bin/tini -- /u…"   31 minutes ago   Up 31 minutes (healthy)     0.0.0.0:8000->8000/tcp                                edd-http-1
e6f1d2ec3a34   postgres:11                           "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes               5432/tcp                                              edd-ice_db-1
ec47e37a1b47   jbei/ice:latest                       "catalina.sh run"        31 minutes ago   Up 31 minutes (healthy)     0.0.0.0:8080->8080/tcp                                edd-ice-1
bce8014eab37   jbei/rabbitmq:3.7-management-alpine   "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes               4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   edd-rabbitmq-1
47d8f2c5a732   postgres:11                           "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes               5432/tcp                                              edd-postgres-1
736bac1d4ae0   jbei/redis:5                          "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes (healthy)     6379/tcp                                              edd-redis-1
5b54916c37e1   jbei/solr:8                           "/entrypoint.sh"         31 minutes ago   Up 31 minutes (healthy)     8983/tcp                                              edd-solr-1
2357bcb70427   jbei/nginx:mainline                   "/docker-entrypoint.…"   31 minutes ago   Up 31 minutes (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp              edd-nginx-1
242421ec502e   tianon/exim4                          "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes               25/tcp                                                edd-smtp-1

# edd-worker-1
% docker logs bbdcec022a65
+ invoke celery
Running with mounted copy of code …
Loading settings from /etc/edd …
cp: cannot create regular file './local/./__init__.py': File exists

#edd-websocket-1
 % docker logs 5a4cdf66428a
+ invoke daphne
Running with mounted copy of code …
Loading settings from /etc/edd …
cp: cannot create regular file './local/./example': File exists

P.S. My docker env. is empty i.e. no image/container/volume when I started out.

Thanks.

**Comment by wmorrell** [comment]
Sorry, I cannot help remotely troubleshooting Docker issues. The errors look like you're mounting code/settings that are not read/write accessible to the containers. You'll need to find someone else to help diagnose the problem with your Docker setup.
